### ISSUE TITLE
go get fails with this repo as dependency

### ISSUE THREAD

**Issue by sudo-suhas** [rsc/qr#2]
I faced an unexpected error while trying to `go get github.com/claudiodangelis/qr-filetransfer` through a 2 level dependency chain:
```
➜ GOPATH=~/installs/go-tools go get -u -v github.com/claudiodangelis/qr-filetransfer
github.com/claudiodangelis/qr-filetransfer (download)
github.com/jhoonb/archivex (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-isatty (download)
github.com/mdp/qrterminal (download)
github.com/rsc/qr (download)
package github.com/rsc/qr: code in directory /home/suhaskaranth/installs/go-tools/src/github.com/rsc/qr expects import "rsc.io/qr"
```
Specifically, `github.com/claudiodangelis/qr-filetransfer ➜ github.com/mdp/qrterminal ➜ github.com/rsc/qr`. My understanding was that this was due to an incorrect import of this module - [mdp/qrterminal:qrterminal.go@`44bd8ed`#L7](https://github.com/mdp/qrterminal/blob/44bd8ed8853057e8f960c0a1126a2f23e82c3703/qrterminal.go#L7). And I opened a PR to correct the same - mdp/qrterminal#10. I wanted to confirm that this is indeed the right course of action and no change is required in this module, hence this issue.

**Comment by AnthonyLansangan** [comment]
Hi @sudo-suhas , you should get this using "go get [-u] rsc.io/qr" instead of "github.com/rsc/qr".
Correct import path is rsc.io/qr.

**Comment by AnthonyLansangan** [comment]
Hi @sudo-suhas , you are correct. I also encountered same issue when I used this as a dependency of my project. But it was my bad because I used github.com/rsc/qr instead of rsc.io/qr.

**Comment by sudo-suhas** [comment]
I understand that if I want to use this library, I should refer to it as `rsc.io/qr`. However, in this instance, the issue is stemming from a transient dependency trying to import `rsc.io/qr` incorrectly. As I mentioned, I have a created a PR to the module in question with this correction. However, note that this incorrect dependency declaration was not causing a build error earlier and has only started happeining after ca9a01f which asserted the import path.

**Comment by sudo-suhas** [comment]
The PR in mdp/qrterminal was merged, closing this issue.
